config/routes.rb
Rails.application.routes.draw do
  root to: "photos#index"

  get  "/sign-up"                , to: "users#sign_up", as: :sign_up
  post "/users/:user_id"         , to: "users#update" , as: :update_user
  post "/users"                  , to: "users#create" , as: :new_user
  get  "/users/:user_id"         , to: "users#show"   , as: :user

  post "/sign-in"                , to: "sessions#sign_in" , as: :sign_in
  get  "/sign-out"               , to: "sessions#sign_out", as: :sign_out

  get    "/"                     , to: "photos#index"
  get    "/photos/new"           , to: "photos#new"    , as: :new_photo
  get    "/photos/ranked"        , to: "photos#ranked" , as: :ranked
  get    "/photos/:photo_id"     , to: "photos#show"   , as: :photo
  post   "/photos"               , to: "photos#add"    , as: :add_photo
  patch  "/photos/:photo_id"     , to: "photos#update" , as: :update_photo
  delete "/photos/:photo_id"     , to: "photos#delete" , as: :delete_photo

  post "/photos/:photo_id/rate"  , to: "ratings#create"   , as: :rating

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :title, presence: true
  validates :image_file, presence: true

  belongs_to :user
  has_many   :ratings

  mount_uploader :image_file, ImageFileUploader

  # validates :title, presence: true

  # class method(s):
  def self.random
    self.order("RANDOM()").first
  end

  # instance method(s):
  def rating_score
    # self.ratings.to_a.sum do |r|
    #   r.rating
    # end

    self.ratings.sum(:rating)
  end

  def ratings_digest
    if self.ratings
       self.rating_score.to_s +
       "Bad:  #{self.ratings.where(rating:1).count} ".to_s +
       "Meh:  #{self.ratings.where(rating:2).count} ".to_s +
       "Good: #{self.ratings.where(rating:3).count} ".to_s
    end
  end

  def bad_ratings_count
    self.ratings.where(rating:1).count
  end

  def meh_ratings_count
    self.ratings.where(rating:2).count
  end

  def good_ratings_count
    self.ratings.where(rating:3).count
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  validates :rating, presence: true

  belongs_to :photo
  belongs_to :user

  def username
    self.user.username
  end

  def formatted_comment
    # absract code from photo 'show' view, for comments on each photo w/ link to username, into here
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness:true
  validates :email, format: {with: /@/}
  validates :username, presence: true, uniqueness:true

  has_many :photos
  has_many :ratings

  def avatar
    default_url = "http://placekitten.com/300/301"
    gravatar_id = Digest::MD5.hexdigest(self.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?d=#{CGI.escape(default_url)}"
  end

  # add random_photo method

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end
  before_action :set_current_user

  def random_photo
    if @current_user
      not_by_user = Photo.where.not(user_id: @current_user.id)
      can_be_rated = []
      can_be_rated = not_by_user.select do |p|
        p.ratings.where(user_id: @current_user.id).empty?
          # alternate syntax:
          # !p.ratings.exists?(user_id: @current_user.id)
      end

      if can_be_rated.empty? == true
        return nil
        redirect_to root_path, notice: "You have reviewed every photo!"
      else
        can_be_rated.sample.id
      end

    elsif @current_user == nil
      photo = Photo.order("RANDOM()").first
      if photo
        photo.id
      end
    end
  end
  helper_method :random_photo

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  def show
    @photo  = Photo.find(params[:photo_id])
  end

  def update
    @photo             = Photo.find(params[:photo_id])
    @photo.title       = params[:photo][:title]
    @photo.description = params[:photo][:description]
    @photo.image_file  = params[:photo][:image_file]
    @photo.save
    redirect_to photo_path(@photo.id)
  end

  def new
    @photo             = Photo.new
  end

  def add
    @photo             = Photo.new
    @photo.user_id     = @current_user.id
    @photo.title       = params[:photo][:title]
    @photo.description = params[:photo][:description]
    @photo.image_file  = params[:photo][:image_file]
    if @photo.save
      redirect_to photo_path(@photo.id)
    else
      render :new
      # @photos = Photo.all
      # render :photos

      # @photo = Photo.find(params[:photo_id])
      # render "/photos/show"
    end
  end

  def delete
    @photo = Photo.find(params[:photo_id])
    @photo.destroy
    redirect_to root_path
  end

  def ranked
    @photos = Photo.all
    @sorted = @photos.sort_by {|p| p.rating_score}
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :image_file)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new
    if params[:rating] == "bad"
      @rating.rating = 1
    elsif params[:rating] == "meh"
      @rating.rating = 2
    elsif params[:rating] == "good"
      @rating.rating = 3
    end
    @rating.comment  = params[:comment]
    @rating.photo_id = params[:photo_id]
    @rating.user_id  = @current_user.id
    if @rating.save
      @photo = Photo.find(params[:photo_id])
      @photographer = User.find(@photo.user_id)
      if @photographer.accept_rating_email == true
        # first arg is photo owner, second arg is reviewer, third is the rating object itself
        UserMailer.reviewed(@photographer.id,@rating.user_id,@rating.id,@photo.id).deliver_now
        redirect_to photo_path(@rating.photo_id)
      else
        redirect_to photo_path(@rating.photo_id)
      end
    else
      @photo = Photo.find(params[:photo_id])
      render "/photos/show"
    end
  end

  def ranked

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def sign_in
      @user = User.find_by(username: params[:username])
      if @user == nil
        redirect_to root_path, notice: "Wrong username or password"
      elsif @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to root_path, notice: "Wrong username or password"
      end
    end

    def sign_out
      session.delete(:user_id)
      redirect_to "/"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up

  end

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password, :password_confirmation, :accept_rating_email))
    if @user.save
      session[:user_id] = @user.id
      # UserMailer.subscribe(@user.id).deliver_now
      redirect_to root_path, notice: "Registration Successful. Welcome to ImageRater!"
    else
      render :sign_up
    end
  end

  def show
    @user = User.find(params[:user_id])
  end

  def update
    @user                     = User.find(params[:user_id])
    @user.accept_rating_email = params[:receive]
    @user.email = params[:email] if params[:email]
    if @user.save
      redirect_to user_path(@user.id)
    else
      render "users/show"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_account_details.html.erb
<div class="row">
  <div class="col-sm-12 user-account-container">
    <h2>Account details for: <span class="username"><%= @current_user.username %></span></h2>
    <div class="user-account-details col-lg-12">
        <div class="col-lg-6">
          <strong>Avatar:</strong> <%= image_tag @current_user.avatar, :class=>"avatar avatar-img-show"%>
        </div>
        <div class="col-lg-6">
          <strong>Member since:</strong> <%= @current_user.created_at.strftime("%B %d, %Y")%>
        </div>
    </div>
    <div class="user-email-settings col-lg-12">
        <div class="col-lg-12">
          <strong>e-mail settings:</strong>
        </div>
        <%= form_tag update_user_path(@user.id) do %>
          <div class="col-lg-6">
            <div class="form-group update-email-address-form col-lg-8">
              <input type="email", name="email", placeholder="<%= @current_user.email%>", class="form-control col-lg-4">
              <input type="submit", value="update e-mail", class="btn btn-md btn-success">
            </div>
          </div>
        <% end %>
      <%= form_tag update_user_path(@user.id) do %>
          <div class="form-group update-email-settings-form col-lg-6">
            <p id="email-update-info">Receive emails when users comment on your photos?</p>
            <%= radio_button_tag(:receive, true, :checked => @user.accept_rating_email == true) %>
            <%= label_tag(:receive_yes, "Yes")  %>
            <%= radio_button_tag(:receive, false, :checked => @user.accept_rating_email == false) %>
            <%= label_tag(:receive_no, "No")      %>

            <%= submit_tag "submit", class: "btn btn-md btn-success"%>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_edit_photo_form.html.erb
<div class="row">
  <div class="edit-photo-container col-lg-12">
    <h2>Edit Photo</h2>
    <%= form_for @photo do |f| %>
      <div class="field">
        <%= f.label      :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label      :description %>
        <%= f.text_field :description %>
      </div>
      <div class="field">
        <%= f.label      :image_file %>
        <%= f.file_field :image_file %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
    <form action="/photos/<%=@photo.id%>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" class="btn btn-md btn-danger delete-photo-btn" value="Delete" data-confirm:"Are you sure?">
    </form>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <!-- flash notice logic goes here, or possibly in its own partial -->
  <div class="container">
    <div class="navbar-header">
      <a><%= link_to "PhotoSquid", root_path, class:"navbar-brand" %></a  >

      <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Rankings", ranked_path %></li>
        <% if random_photo %>
          <li><%= link_to "Random", photo_path(random_photo) %></li>
        <% else %>
          <li><a id="ratings-closed">No photos left to rate!</a></li>
        <% end %>
      </ul>
      <div class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <ul class="logged-in-user">
            <li><a id="greeting">Hello, <span class="username"><%= @current_user.username%></span></a></li>
            <li><%= image_tag @current_user.avatar, :class=>"avatar avatar-header" %></li>
            <li><%= link_to "My Account"    , user_path(@current_user.id)%> </li>
            <li><%= link_to "Sign Out"      , sign_out_path%>            </li>
          </ul>
        <% else %>
          <%= render "layouts/sign_in_form" %>
          <!-- <button class="btn btn-success btn-md", id="create-acct-btn"><%= link_to "Sign Up", sign_up_path %> </button> -->
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_rating_form.html.erb
<form action="/photos/<%= @photo.id%>/rate" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
  <div class="btn-group" data-toggle="buttons">
    <label class="btn btn-danger">
      <input type="radio" name="rating" id="rating_bad" value="bad"> Bad (<%= @photo.bad_ratings_count %>)
    </label>
    <label class="btn btn-warning">
      <input type="radio" name="rating" id="rating_meh" value="meh"> Meh (<%= @photo.meh_ratings_count %>)
    </label>
    <label class="btn btn-success">
      <input type="radio" name="rating" id="rating_good" value="good"> Good (<%= @photo.good_ratings_count %>)
    </label>
  </div>
  <textarea name="comment"id="review-comment-field" placeholder="comment(optional)"></textarea>
  <button name="button" type="submit" class="btn btn-primary submit-review-btn">Submit</button>
</form>

<% if @rating %>
  <% if @rating.errors.any? %>
    <% @rating.errors.each do |column, message| %>
      <ul>
        <li>
          <strong><%= column.capitalize %>:</strong> <%= message %>
        </li>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_ratings_summary.html.erb
<h3>Ratings Summary</h3>
Bad: <%= @photo.ratings.where(rating:1).count %>
Meh: <%= @photo.ratings.where(rating:2).count %>
Good: <%= @photo.ratings.where(rating:3).count %>

app/views/layouts/_sign_in_form.html.erb
<div class="navbar-form-wrapper">
  <%= form_tag sign_in_path, class:'navbar-form' do %>
    <div class="form-group">
      <input type="username", name="username", placeholder="username", class="form-control">
    </div>
    <div class="form-group">
      <input type="password", name="password", placeholder="password", class="form-control">
    </div>
    <input type="submit", value="Sign In", class="btn btn-md btn-primary">
  <% end %>
  <button class="btn btn-success btn-md", id="create-acct-btn"><%= link_to "Sign Up", sign_up_path %> </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoSquid </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Croissant+One|Cantarell' rel='stylesheet' type='text/css'>
</head>
<body>

  <%= render "layouts/navbar" %>

  <div class="container page-content">
    <%= yield %>
  </div>

</body>
</html>

app/views/photos/index.html.erb
<div class="all-photos">
  <div class="row">
    <% @photos.shuffle.in_groups_of(2, false).each do |group| %>
        <% group.each do |p| %>
          <div class="col-sm-12 col-md-6 col-lg-4 index-photo-block">
            <%= link_to image_tag(p.image_file.index, :class => "photo-index-version"), photo_path(p.id)%>
            <div class="col-sm-12 col-lg-6 index-photo-details">
              <div class="index-details-left">
                <%= link_to p.title, photo_path(p.id), :class => "photo-name" %>
              </div>
              <div class="index-details-right">
                <span>by</span> <span class="username"><%=link_to p.user.username, user_path(p.user.id)%></span>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

<div class="add-photo-container">
  <div class="row">
    <div class="col-xs-8 col-xs-push-2 col-md-4 col-md-push-4 add-photo-btn-wrapper">
      <button class="btn btn-lg btn-info add-photo-btn">
        <%= link_to "Add new photo", new_photo_path %>
      </button>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="row">
  <div class="add-photo-form col-lg-6 col-lg-push-3 col-sm-12 ">
      <div class="add-photo-form-header">
        <h1>Add Photo</h1>
      </div>
      <%= form_for @photo, url: add_photo_path do |f| %>
      <div class="form-group signup-input">
        <%= f.label      :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="form-group signup-input">
        <%= f.label      :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="form-group signup-input">
        <%= f.label      :image_file %><br>
        <%= f.file_field :image_file %>
      </div>
      <div>
        <%= f.submit id: :submit_new_photo%>
      </div>
    <% end %>
  </div>
</div>

<div class="errors-container">
  <% if @photo %>
    <% if @photo.errors.any? %>
      <% @photo.errors.each do |column, message| %>
        <ul>
          <li>
            <strong><%= column.capitalize %>:</strong> <%= message %>
          </li>
        </ul>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/photos/ranked.html.erb
<h1>Rankings</h1>
  <div class="all-photos-ranked">
    <% @sorted.reverse.in_groups_of(4, false).each do |group| %>
      <div class="row">
        <% group.each do |p| %>
          <div class="col-xs-6 col-sm-3 ranked-photo-block ">
            <span class="rating-score"> <%= p.rating_score %></span>
            <%= link_to image_tag(p.image_file.index, :class => "photo-ranked-version"), photo_path(p.id) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/photos/rate.html.erb
<h1>RATE PHOTO: <%= @photo.title %></h1>

app/views/photos/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="photo-container">
      <div class="row">
        <div class="photo-image-container col-sm-9">
          <%= image_tag @photo.image_file.detail, :id => "photo-detail-version" %>
          <p id="photo-title"><%= @photo.title %></p>
          <p id="photo-description"><%= @photo.description %></p>
        </div>

        <div class="photo-details-container col-sm-3">
          <div class="details-top">
            <%= link_to (image_tag @photo.user.avatar, :class=>"avatar avatar-img-show"), user_path(@photo.user.id) %>
            <span>By
              <% if @photo.user %>
                <span class="username"><%= link_to @photo.user.username, user_path(@photo.user.id) %></span>
              <% else %>
                anonymous
              <% end %>
              <br>
            </span>
          </div>
          <div class="details-rating-form">
            <% if @current_user == nil%>
                <h5>You must be logged in to rate photos.</h5>
            <% elsif @current_user %>
              <% if @photo.user_id != @current_user.id %>
                <%= render "layouts/rating_form" %>
              <% else  %>
                <h5>Sorry, you can't rate your own photos.</h5>
              <% end  %>
            <% end  %>
          </div>
          <div class="details-comment-list">
            <div class="comment-list">
              <h3>Comments</h3>
              <% if @photo.ratings.count > 0 == true %>
                <% @photo.ratings.reverse.each do |r| %>
                  <% if r.comment != "" %>
                    <p>
                      <span class="username"><%= link_to r.username, user_path(r.user.id)%></span>:
                      <%= r.comment %>
                      <span class="comment-time"><%= r.created_at.strftime("%b %e '%y")%></span>
                    </p>
                  <% end %>
                <% end %>
              <% else %>
                <h5>Nobody has commented on this photo!</h5>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @current_user %>
  <% if @photo.user_id == @current_user.id %>
    <%= render "layouts/edit_photo_form" %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if @current_user %>
  <% if @current_user.id == @user.id %>
    <%= render "layouts/account_details" %>
  <% end %>
<% end %>

<div id="user-avatar-title">
  <%= image_tag @user.avatar, :class=>"avatar avatar-img-show" %>
  <h2><span class="username"><%= @user.username.capitalize %></span>'s  Images</h2>
</div>

<div class="row">
  <% @user.photos.sort.in_groups_of(2, false).each do |group| %>
      <% group.each do |p| %>
        <div class="col-xs-6 col-sm-6 col-lg-3 preview-photo-block">
          <%= link_to image_tag(p.image_file.index, :class => "photo-preview-version"), photo_path(p.id) %><br>
          <span class="photo-upload">uploaded on: <%= p.created_at.strftime("%m/%d/%Y") %></span>
        </div>
      <% end %>
  <% end %>
</div>

app/views/users/sign-up.html.erb
<div class="row">
  <div class = "signup-container col-lg-6 col-xs-10">
    <form action="/users" method="POST" class="signup-form">
      <h1>Sign Up</h1>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
      <div class="form-group username-group">
        <input type='text' name="user[username]" class="form-control" placeholder="username">
      </div>
      <div class="form-group email-group">
        <input type='text' name="user[email]" class="form-control" placeholder="e-mail address">
      </div>
      <div class="form-group pw-group">
        <input type="password" name="user[password]"  class="form-control" placeholder="Password">
      </div>
      <div class="form-group pw-confirm-group">
        <input type="password" name="user[password_confirmation]" class="form-control" placeholder="Confirm password">
      </div>

      <button type='submit' class="btn btn-primary btn-block" >Create Account</button>
    </form>
  </div>
</div>

<% if @user %>
  <% if @user.errors.any? %>
    <% @user.errors.each do |column, message| %>
      <ul>
        <li>
          <strong><%= column.capitalize %>:</strong> <%= message %>
        </li>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/users/sign_up.html.erb
<div class="row">
  <div class = "col-xs-12 col-sm-10 col-sm-push-3 col-md-push-4">
    <div class="signup-container">
      <form action="/users" method="POST" class="signup-form">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <div class="signup-input signup-header">
          <h1>Sign Up</h1>
        </div>
        <div class="username-group">
          <input type='text' name="user[username]" class="form-control signup-input" placeholder="username">
        </div>
        <div class="email-group">
          <input type='text' name="user[email]" class="form-control signup-input" placeholder="e-mail address">
        </div>
        <div class="pw-group">
          <input type="password" name="user[password]"  class="form-control signup-input" placeholder="Password">
        </div>
        <div class="pw-confirm-group">
          <input type="password" name="user[password_confirmation]" class="form-control signup-input" placeholder="Confirm password">
        </div>

        <button type='submit' class="btn btn-primary create-acct-btn" >Create Account</button>
      </form>
    </div>
  </div>
</div>

<% if @user %>
  <% if @user.errors.any? %>
    <% @user.errors.each do |column, message| %>
      <ul>
        <li>
          <strong><%= column.capitalize %>:</strong> <%= message %>
        </li>
      </ul>
    <% end %>
  <% end %>
<% end %>